export const FETCH_IN_PROGRESS = 'FETCH_IN_PROGRESS';
export const SAVE_IN_PROGRESS = 'SAVE_IN_PROGRESS';
export const FETCHED = 'FETCHED';
export const FETCH_ERROR = 'FETCH_ERROR';

export const CLIENT_CREATED = 'CLIENT_CREATED';
export const CLIENT_UPDATED = 'CLIENT_UPDATED';
export const CLIENT_CREATE_ERROR = 'CLIENT_CREATE_ERROR';
export const CLIENT_UPDATE_ERROR = 'UPDATE_UPDATE_ERROR';
