const constants = {
    ARG_HASH: 'hash',
    ARG_TXID: 'txid',
    ARG_POSITION: 'position',
    ARG_COMMITMENT: 'commitment',
    ARG_MERKLE_ROOT: 'merkle_root',
    BAD_LENGTH_TXID: 'txid string parameter must contain 64 characters',
    BAD_LENGTH_COMMITMENT: 'commitment string parameter must contain 64 characters',
    BAD_TYPE_POSITION: 'position expects a int',
    COMMITMENT_POSITION_UNKNOWN: 'your commitment or position is unknown to us',
    AWAITING_ATTESTATION: 'Slot activated: awaiting first attestation',
    FREE_TIER_LIMIT: 'Daily commitment limit reached',
    INTERNAL_ERROR_API: 'an error occurred in the API',
    NO_ADDITIONS: 'additions not supported at this service tier',
    LIMIT_ADDITIONS: 'addition limit per attestation reached',
    AWAITING_ATTEST: 'Slot allocated: awating first attestation',
    MERKLEROOT_UNKNOWN: 'your merkle root is unknown to us',
    MISSING_ARG_TXID: 'missing txid parameter',
    MISSING_ARG_HASH: 'missing hash parameter',
    MISSING_ARG_APIKEY: 'missing X-MAINSTAY-APIKEY',
    MISSING_ARG_COMMITMENT: 'missing commitment parameter',
    MISSING_ARG_MERKLE_ROOT: 'missing merkle_root parameter',
    MISSING_ARG_PAYLOAD: 'missing X-MAINSTAY-PAYLOAD',
    BAD_ARG_PAYLOAD: 'X-MAINSTAY-PAYLOAD not in base64 format',
    MISSING_ARG_POSITION: 'missing position parameter',
    MISSING_ARG_SIGNATURE_APIKEY: 'missing X-MAINSTAY-SIGNATURE-APIKEY',
    MISSING_ARG_SIGNATURE: 'missing X-MAINSTAY-SIGNATURE',
    MISSING_PAYLOAD_TOKEN: 'missing token parameter in payload',
    NS_PER_SEC: 1000000000,
    PARAM_UNDEFINED: 'parameter undefined',
    PAYLOAD_TOKEN_ERROR: 'your token is wrong',
    POSITION_UNKNOWN: 'your position is unknown to us',
    SIGNATURE_INVALID: 'your signature is incorrect',
    SIZE_TXID: 64,
    SIZE_COMMITMENT: 64,
    SIZE_MERKLE_ROOT: 64,
    TXID_UNKNOWN: 'attestation could not be found for the txid provided',
    TYPE_ERROR: 'an error is present in your type',
    TYPE_UNKNOWN: 'type unknown',
    VERSION_API_V1: 'Mainstay-API-v1',
    MAINSTAY_PAYLOAD: 'X-MAINSTAY-PAYLOAD',
    MAINSTAY_SIGNATURE: 'X-MAINSTAY-SIGNATURE',
    DATA: 'data',
    VALUE: 'value',
};

constants.BAD_LENGTH_MERKLE_ROOT = constants.BAD_LENGTH_COMMITMENT;

module.exports = constants;