export const FETCH_IN_PROGRESS = 'CLIENT_SIGN_UP_FETCH_IN_PROGRESS';
export const FETCHED = 'CLIENT_SIGN_UP_FETCHED';
export const FETCH_ERROR = 'CLIENT_SIGN_UP_FETCH_ERROR';

export const UPDATE_STATUS_IN_PROGRESS = 'CLIENT_SIGN_UP_UPDATE_STATUS_IN_PROGRESS';
export const UPDATE_STATUS_DONE = 'CLIENT_SIGN_UP_UPDATE_STATUS_DONE';
export const UPDATE_STATUS_ERROR = 'CLIENT_SIGN_UP_UPDATE_STATUS_ERROR';
